### ISSUE TITLE
Stuck at Quick Raid screen

### ISSUE THREAD

**Issue by Revuin** [fabian57fabian/archero_bot_57#28]
After tapping "Play", the Quick Raid screen appears but the bot ignores this and continues playing as if the dungeon started. 

 - Nox Emulator version 7.0.3.1
 - Screen size: 1080x1920
 - Computer OS: Windows 10

![image](https://user-images.githubusercontent.com/20654538/179627380-8dcbe8be-869c-4ba4-aa57-d8fc056b0e83.png)

**Comment by fabian57fabian** [comment]
Fixed with last commit 83db8936755f4aac7d752ec5d4d2f57bced3502d .
Please try and let me know. It is currently playing my 12th game and still going

**Comment by Revuin** [comment]
Thanks for working on it so quickly! Unfortunately, it's still not working on my end. I even confirmed that your new changes are in the static_coords.json

![image](https://user-images.githubusercontent.com/20654538/179634968-1e9fe0d8-d3a6-4f6e-b049-962ec3f2f9ba.png)

**Comment by fabian57fabian** [comment]
Are you sure you pulled the last commit?
If so, please open TouchManager.py, once comnected take a screenshot of your nox screen having the "quick raid" page and save it. Then:
- in the left list select the new image,

**Comment by Revuin** [comment]
Yes, I downloaded a new zip, and even opened the json file you changed and made sure the new changes are in there.

TouchManager.py won't open. I'm getting the same error reported in https://github.com/fabian57fabian/archero_bot_57/issues/27

![image](https://user-images.githubusercontent.com/20654538/179635827-f1714cd5-f870-4552-99f6-83a1f4b22fbe.png)

**Comment by Revuin** [comment]
Here it is. I followed the link in the guide to install Python but it seems to be on an older version

![image](https://user-images.githubusercontent.com/20654538/179793128-02387ee9-99a4-4634-adfb-9b95a89a812e.png)
